version: 0.2

run-as: Linux-user-name
  
phases:
  install:
    runtime-versions:
      java: openjdk12
    commands:
      - echo install   
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - gradle build
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - build/libs/project-management-service-0.0.1-RELEASE.jar