DROP TABLE IF EXISTS EMP_DEPART_MAP;
DROP TABLE IF EXISTS PROJ_EMP_MAP;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
	DEPART_ID  varchar(50) NOT NULL PRIMARY KEY,
       DEPT_NAME varchar(50) NOT NULl
);

CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID varchar(50) NOT NULL PRIMARY KEY, 
	EMP_FIRST_NAME varchar(50) NOT NULL,
	EMP_LAST_NAME varchar(50) NOT NULL);

CREATE TABLE PROJECT(
	PROJ_ID varchar(50) NOT NULL , 
	DEPART_ID varchar(50) NOT NULL ,
	PROJ_NAME varchar(50) NOT NULL,
      PRIMARY KEY(PROJ_ID,DEPART_ID),
      FOREIGN KEY (DEPART_ID) REFERENCES DEPARTMENT(DEPART_ID));

CREATE TABLE EMP_DEPART_MAP(
	DEPART_ID varchar(50) NOT NULL,
	EMPLOYEE_ID varchar(50) NOT NULL,
FOREIGN KEY(DEPART_ID) REFERENCES DEPARTMENT(DEPART_ID) ,
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
CONSTRAINT UC_EMP_DEPART_MAP UNIQUE(DEPART_ID,EMPLOYEE_ID));

CREATE TABLE PROJ_EMP_MAP(
	PROJ_ID varchar(50) NOT NULL,
	DEPART_ID varchar(50) NOT NULL,
	EMPLOYEE_ID varchar(50) NOT NULL,
FOREIGN KEY(PROJ_ID,DEPART_ID) REFERENCES PROJECT(PROJ_ID,DEPART_ID),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
CONSTRAINT UC_PROJ_EMP_MAP UNIQUE(PROJ_ID,DEPART_ID,EMPLOYEE_ID));

